== Parameters

You have the possibility to tweak the configuration using environment variables. Below is an overview of some key configuration parameters.

|===
|Parameter | default | Description

| `KAFKA_BOOTSTRAP_SERVERS`
| _<mandatory>_
| Kafka bootstrap servers

| `SYNTH_CLIENT_TOPIC`
| _<mandatory>_
| The Kafka topic to produce to and consume from.

| `SYNTH_CLIENT_MESSAGES_MESSAGE_SIZE_BYTES`
| 8
| The size of each Kafka message in bytes.

| `SYNTH_CLIENT_MESSAGES_MESSAGES_PER_SECOND`
| 1
| The number of messages to produce per second.

| `SYNTH_CLIENT_MESSAGES_MESSAGES_IGNORE_FIRST_N_MESSAGES`
| 1
| The number of messages (per partition) to ignore before starting to measure latencies. This is useful for avoiding adding noise to the metrics when the consumer group is being rebalanced. The default value should be sufficient.


| `SYNTH_CLIENT_RACK`
| "default"
| Some identifier of the environment in which the client is running. For example "eu-west-1a". This is useful for measuring latencies between clients that are running in different environments. Can be left unset if not needed. If you have multiple racks, then be sure to assign a unique consumer group ID to each rack.

| `QUARKUS_HTTP_PORT`
| 8081
| The port on which the metrics endpoint will be exposed.
|===

Furthermore, any environment variable prefixed with `KAFKA_` will be interpreted as a Kafka Producer/Consumer configuration property.
For example, setting `KAFKA_GROUP_ID` will set the value of the `group.id` consumer property.

`KAFKA_CONFIG_PROVIDERS` are supported like `file` or `env`. For example, setting `KAFKA_CONFIG_PROVIDERS=file` will load the configuration from a file.
`KAFKA_CONFIG_PROVIDERS_FILE_CLASS` will be used to define the provider class. For example, setting `KAFKA_CONFIG_PROVIDERS_FILE_CLASS=org.apache.kafka.common.config.provider.FileConfigProvider` will load the configuration from a file.

Be aware that e.g. `${file:/path/to/file}` needs to be escaped in the environment variable. For example, `KAFKA_CONFIG_PROVIDERS_FILE_PATH=\${file:/path/to/file}` otherwise quarkus will try to resolve it as variable and you will see `Error injecting java.util.Map<java.lang.String, java.lang.String> io.spoud.kafka.KafkaFactory.config`.

