package io.spoud.ui;

import io.quarkus.logging.Log;
import io.vertx.ext.web.Router;
import jakarta.annotation.PostConstruct;
import jakarta.enterprise.event.Observes;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import org.eclipse.microprofile.config.inject.ConfigProperty;
import org.jsoup.Jsoup;

@Path("/")
public class IndexRoute {
    @ConfigProperty(name = "quarkus.http.root-path")
    String rootPath;

    // This template is generated by Vite when you run `npm run build`. Do not commit it, as it is a build-time artifact
    String indexHtml;

    // We pre-render the index template at startup by adding the <base...> tag if needed and rewiring
    // asset links such that they are relative to the root path. This is necessary for ensuring that deep-linking works correctly
    @PostConstruct
    void prerender() {
        try (var originalHtmlStream = getClass().getClassLoader().getResourceAsStream("templates/index.html")) {
            var rp = rootPath.endsWith("/") ? rootPath : rootPath + "/";
            var doc = Jsoup.parse(originalHtmlStream, "UTF-8", "/");
            if (!rp.equals("/")) {
                doc.head().prependElement("base").attr("href", rp);
            }
            doc.head().select("link")
                    .stream()
                    .filter(e -> !e.attr("href").startsWith("https://"))
                    .forEach(e -> e.attr("href", rp + e.attr("href")));
            doc.head().select("script")
                    .stream()
                    .filter(e -> !e.attr("src").startsWith("https://"))
                    .forEach(e -> e.attr("src", rp + e.attr("src")));
            indexHtml = doc.toString();
        } catch (Exception e) {
            Log.error("Failed to prerender index.html", e);
            indexHtml = "Error: Template could not be rendered.";
        }
    }

    @GET
    @Produces(MediaType.TEXT_HTML)
    public String index() {
        return indexHtml;
    }

    /* SPA ROUTING */
    void init(@Observes Router router) {
        Log.info("Initializing SPA routing for root path: " + rootPath);
        var rp = rootPath.endsWith("/") ? rootPath : rootPath + "/";
        // any path that doesn't resolve to a resource will be rerouted to index.html where client-side routing will be attempted
        router.getWithRegex("/.*").last().handler(rc -> {
            if (rc.normalizedPath().equals(rp)) {
                rc.fail(404);
            } else {
                rc.reroute(rp);
            }
        });
    }
}
