package io.spoud.ui;

import io.quarkus.logging.Log;
import io.quarkus.qute.Template;
import io.vertx.ext.web.Router;
import jakarta.enterprise.event.Observes;
import jakarta.inject.Inject;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import org.eclipse.microprofile.config.inject.ConfigProperty;

@Path("/")
public class IndexRoute {
    @ConfigProperty(name = "quarkus.http.root-path")
    String rootPath;

    // This template is generated by Vite when you run `npm run build`. Do not commit it, as it is a build-time artifact
    @Inject
    Template index;

    @GET
    @Produces(MediaType.TEXT_HTML)
    public String index() {
        return index.data("rootPath", rootPath.equals("/") ? "" : rootPath).render();
    }

    /* SPA ROUTING */
    void init(@Observes Router router) {
        Log.info("Initializing SPA routing for root path: " + rootPath);
        var rp = rootPath.endsWith("/") ? rootPath : rootPath + "/";
        // any path that doesn't resolve to a resource will be rerouted to index.html where client-side routing will be attempted
        router.getWithRegex("/.*").last().handler(rc -> {
            if (rc.normalizedPath().equals(rp)) {
                rc.fail(404);
            } else {
                rc.reroute(rp);
            }
        });
    }
}
