name: GitHub Pages Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: asciidoctor-ghpages
        uses: manoelcampos/asciidoctor-ghpages-action@9527ff583929b1000c23c209123bba4e98a21f08 # v2
        with:
          pdf_build: true
          asciidoctor_params: -r asciidoctor-diagram
          source_dir: src/docs/
          post_build: 'find . -name "*.svg" | xargs git add -f'
